version: '3.5'
services:
  wallet-api:
    build: .
    ports:
      - '${PORT}:3000'
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app
    command: pnpm run start:prod

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - '4444:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
